title: ELIXIR IT Training Platform
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ELIXIR IT Training Platform
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Italian elixir platform of training!"
# Metadata description of the website

jekyll:
  watch: true
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@toc-side 
baseurl: "/site"


sass:
  style: compressed
  sourcemap: never

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE



defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: elixir_IT_training
      search_exclude: false
  -
    scope:
      path: "pages/training_courses/TEMPLATE_training_courses.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true 
  -
    scope:
      path: "pages/trainers/TEMPLATE_trainers.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true       
  -
    scope:
      path: "pages/training_courses"
    values:
      type: training_courses 
  -
    scope:
      path: "pages/archive"
    values:
      type: archive      
  -   
    scope:
      path: "pages/trainers"
    values:
      type: trainers



















plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
