title: ELIXIR-IT Training Platform
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ELIXIR-IT Training Platform
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Italian elixir platform of training!"
# Metadata description of the website


remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

baseurl: "/site"


sass:
  style: compressed
  sourcemap: never

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: elixir_IT_Training
      search_exclude: false















plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick
