title: ELIXIR-IT Training Platform
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ELIXIR-IT Training Platform
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Italian elixir platform of training!"
# Metadata description of the website


remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

baseurl: "/site"


sass:
  style: compressed
  sourcemap: never

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: elixir_IT_Training
      search_exclude: false
  -
    scope:
      path: "pages/training_events/TEMPLATE_training_events.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true 
  -
    scope:
      path: "pages/trainers/TEMPLATE_trainers.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true       
  -
    scope:
      path: "pages/training_events"
    values:
      type: training_events 
  -
    scope:
      path: "pages/archive_2023"
    values:
      type: archive_2023 
  -
    scope:
      path: "pages/archive_2022"
    values:
      type: archive_2022     
  -
    scope:
      path: "pages/archive_2021" 
    values:
      type: archive_2021
  -
    scope:
      path: "pages/archive_2020" 
    values:
      type: archive_2020
  -
    scope:
      path: "pages/archive_2019" 
    values:
      type: archive_2019
  -
    scope:
      path: "pages/archive_2018" 
    values:
      type: archive_2018
  -
    scope:
      path: "pages/*/archive_2017" 
    values:
      type: archive_2017

  -   
    scope:
      path: "pages/trainers"
    values:
      type: trainers
  -
    scope:
      path: "pages/people"
    values:
      sidebar: people
  -
    scope:
      path: "pages/collaborators"
    values:
      sidebar: people



















plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick
