title: ELIXIR IT Training Platform
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ELIXIR IT Training Platform
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Italian elixir platform of training!"
# Metadata description of the website

theme: my-theme

sass:
  style: compressed
  sourcemap: never

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

permalink: /:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main
      
      
  -
    scope:
      path: "training_courses"
      type: "pages"
    values:
      type: training_courses 
      
  -
    scope:
      path: "events"
      type: "pages"
    values:
      type: events  
  -   
    scope:
      path: "trainers"
      type: "pages"
    values:
      type: trainers



















plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
