Luca Alessandrì:
    affiliation: University of Turin, Italy
Marcella Bonanomi:
    affiliation: National Research Council – IBSBC Milan
Pierluigi Caboni:
    affiliation: University of Cagliari, Cagliari
Raffaele Calogero:
    affiliation: University of Turin, Italy
Anna Calì:
    affiliation: Agilent Technologies
Flavio A. Franchina:
    affiliation: University of Ferrara, Ferrara
Daniela Gaglio:
    affiliation: National Research Council – IBSBC Milan
Arnold Knijn:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Luigi Lucini:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Valeria Michelacci:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Clara Musicco:
    affiliation: National Research Council – IBIOM, Bari
Roberto M. Pellegrino:
    affiliation: University of Perugia, Perugia
Loredana Le Pera:
    affiliation: Core Facilities Technical-Scientific Service, National Institute of Health (FAST - ISS), Italy
Luca De Sabato:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Allegra Via:
    affiliation: Sapienza University of Rome, Italy
Leilei Zhang:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
