Leilei Zhang:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Luigi Lucini:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Flavio A. Franchina:
    affiliation: University of Ferrara, Ferrara
Anna Calì:
    affiliation: Agilent Technologies
Roberto M. Pellegrino:
    affiliation: University of Perugia, Perugia
Daniela Gaglio:
    affiliation: National Research Council – IBSBC Milan
Clara Musicco:
    affiliation: National Research Council – IBIOM, Bari
Pierluigi Caboni:
    affiliation: University of Cagliari, Cagliari
Marcella Bonanomi:
    affiliation: National Research Council – IBSBC Milan
