 Alessandrì Luca Alessandrì:
    affiliation: 
 Bonanomi Marcella Bonanomi:
    affiliation: 
 Caboni Pierluigi Caboni:
    affiliation: 
 Calogero Raffaele Calogero:
    affiliation: 
 Calì Anna Calì:
    affiliation: 
 De Sabato Luca De Sabato:
    affiliation: 
 Franchina Flavio A. Franchina:
    affiliation: 
 Gaglio Daniela Gaglio:
    affiliation: 
 Knijn Arnold Knijn:
    affiliation: 
 Le Pera Loredana Le Pera:
    affiliation: 
 Lucini Luigi Lucini:
    affiliation: 
 Michelacci Valeria Michelacci:
    affiliation: 
 Musicco Clara Musicco:
    affiliation: 
 Pellegrino Roberto M. Pellegrino:
    affiliation: 
 Via Allegra Via:
    affiliation: 
 Zhang Leilei Zhang:
    affiliation: 
