Júlia Mir Pedrol:
    affiliation: Centre for Genomic Regulation (CRG), The Barcelona Institute of Science and Technology, Dr. Aiguader 88, Barcelona 08003, Spain)
Victoria Nugnes:
    affiliation: University of Padova, ELIXIR-IT, Italy
Logan Mulroney:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Leilei Zhang:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Luigi Lucini:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Flavio A. Franchina:
    affiliation: University of Ferrara, Ferrara
Fabiola De Marco:
    affiliation: Università di Salerno, Italy
Raoul Bonnal:
    affiliation: IFOM - Research Computing & Data Science Manager
Anna Calì:
    affiliation: Agilent Technologies
Roberto M. Pellegrino:
    affiliation: University of Perugia, Perugia
Tommaso Leonardi:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Daniela Gaglio:
    affiliation: National Research Council – IBSBC Milan
Maria Cristina Aspromonte:
    affiliation: University of Padova, ELIXIR-IT, Italy
Clara Musicco:
    affiliation: National Research Council – IBIOM, Bari
Arnold Knijn:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Ernesto Picardi:
    affiliation: University of Bari, Italy
Francesco Nicassio:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Pierluigi Caboni:
    affiliation: University of Cagliari, Cagliari
Valeria Michelacci:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Erik Garrison:
    affiliation: University of Tennesse Health Science Center
Luana Licata:
    affiliation: University of Rome “Tor Vergata”, ELIXIR-IT, Italy
Allegra Via:
    affiliation: Sapienza University of Rome, Italy
Luca Alessandrì:
    affiliation: University of Turin, Italy
Andrea Guarracino:
    affiliation: University of Tennesse Health Science Center
Adriano Fonzino:
    affiliation: University of Bari, Italy
Teresa Colombo:
    affiliation: Istituto di Biologia e Patologia Molecolari (IBPM - CNR), ELIXIR-IT, Italy
Camilla Ugolini:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Raffaele Calogero:
    affiliation: University of Turin, Italy
Loredana Le Pera:
    affiliation: Core Facilities Technical-Scientific Service, National Institute of Health (FAST - ISS), Italy
Alessandro Silvestris:
    affiliation: University of Bari, Italy
Jose Espinosa-Carrasco:
    affiliation: Centre for Genomic Regulation (CRG), The Barcelona Institute of Science and Technology, Dr. Aiguader 88, Barcelona 08003, Spain)
Luca De Sabato:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Federica Quaglia:
    affiliation: University of Padova, ELIXIR-IT, Italy
Marcella Bonanomi:
    affiliation: National Research Council – IBSBC Milan
