 Adriano Fonzino:
  affiliation: 
 Alessandro Silvestris:
  affiliation: 
 Allegra Via:
  affiliation: 
 Andrea Guarracino:
  affiliation: 
 Anna Calì:
  affiliation: 
 Arnold Knijn:
  affiliation: 
 Camilla Ugolini:
  affiliation: 
 Clara Musicco:
  affiliation: 
 Daniela Gaglio:
  affiliation: 
 Erik Garrison:
  affiliation: 
 Ernesto Picardi:
  affiliation: 
 Fabiola De Marco:
  affiliation: 
 Federica Quaglia:
  affiliation: 
 Flavia Villani University of Tennesse Health Science Center:
  affiliation: 
 Flavio A. Franchina:
  affiliation: 
 Francesco Nicassio:
  affiliation: 
 Leilei Zhang:
  affiliation: 
 Logan Mulroney:
  affiliation: 
 Loredana Le Pera:
  affiliation: 
 Luca Alessandrì:
  affiliation: 
 Luca De Sabato:
  affiliation: 
 Luigi Lucini:
  affiliation: 
 Marcella Bonanomi:
  affiliation: 
 Maria Cristina Aspromonte:
  affiliation: 
 Nancy D’Arminio:
  affiliation: 
 Pierluigi Caboni:
  affiliation: 
 Raffaele Calogero:
  affiliation: 
 Roberto M. Pellegrino:
  affiliation: 
 Teresa Colombo:
  affiliation: 
 Tommaso Leonardi:
  affiliation: 
 Valeria Michelacci:
  affiliation: 
 Victoria Nugnes:
  affiliation: 
