
- Daniela Gaglio, National Research Council – IBSBC Milan
- Marcella Bonanomi, National Research Council – IBSBC Milan
- Flavio A. Franchina, University of Ferrara, Ferrara
- Luigi Lucini, Università Cattolica del Sacro Cuore, Piacenza
- Anna Calì, Agilent Technologies
- Leilei Zhang, Università Cattolica del Sacro Cuore, Piacenza
- Clara Musicco, National Research Council – IBIOM, Bari
- Pierluigi Caboni, University of Cagliari, Cagliari
- Roberto M. Pellegrino, University of Perugia, Perugia


- Raffaele Calogero, University of Turin, Italy  
- Luca Alessandrì, University of Turin, Italy



- Ernesto Picardi, University of Bari, Italy  
- Adriano Fonzino, University of Bari, Italy  
