Nancy D’Arminio:
    affiliation: Università di Salerno, Italy
**Valeria Michelacci** Dep. of Food Safety:
    affiliation: Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Flavia Villani University of Tennesse Health Science Center:
    affiliation: - Flavia Villani - University of Tennesse Health Science Center
Logan Mulroney (IIT:
    affiliation: IT)
Camilla Ugolini (IIT:
    affiliation: IT)
Leilei Zhang:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
**Federica Quaglia** University of Padova:
    affiliation: ELIXIR-IT, Italy
Luigi Lucini:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Flavio A. Franchina:
    affiliation: University of Ferrara, Ferrara
**Arnold Knijn** Dep. of Food Safety:
    affiliation: Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Dott. Cristiano Petrini:
    affiliation: Bioinformatics engineer, IFOM-ETS, Research Computing & Data Science
Fabiola De Marco:
    affiliation: Università di Salerno, Italy
Alessia Pinto:
    affiliation: PhD student, University of Rome “Tor Vergata”, ELIXIR-IT, Italy
Anna Calì:
    affiliation: Agilent Technologies
Roberto M. Pellegrino:
    affiliation: University of Perugia, Perugia
Daniela Gaglio:
    affiliation: National Research Council – IBSBC Milan
**Allegra Via** Sapienza University of Rome:
    affiliation: Italy
Clara Musicco:
    affiliation: National Research Council – IBIOM, Bari
Tommaso Leonardi (IIT:
    affiliation: IT)
Ernesto Picardi:
    affiliation: University of Bari, Italy
Ernesto Picardi (UNIBA:
    affiliation: IT)
Pierluigi Caboni:
    affiliation: University of Cagliari, Cagliari
Francesco Nicassio (IIT:
    affiliation: IT)
Alessandro Silvestris (UNIBA:
    affiliation: IT)
Dott. Riccardo Lorenzo Rossi:
    affiliation: Bioinformatics scientist, IFOM-ETS, Research Computing & Data Science
**Loredana Le Pera** Core Facilities Technical-Scientific Service:
    affiliation: National Institute of Health (FAST - ISS), Italy
Luca Alessandrì:
    affiliation: University of Turin, Italy
Dott. Raoul Bonnal:
    affiliation: IFOM - Research Computing & Data Science Manager
Adriano Fonzino:
    affiliation: University of Bari, Italy
Adriano Fonzino (UNIBA:
    affiliation: IT)
Teresa Colombo:
    affiliation: Istituto di Biologia e Patologia Molecolari (IBPM - CNR), ELIXIR-IT, Italy
Raffaele Calogero:
    affiliation: University of Turin, Italy
Francesco Gregoris:
    affiliation: PhD student, University of Padua
**Maria Cristina Aspromonte**University of Padova:
    affiliation: ELIXIR-IT, Italy
**Luca De Sabato** Dep. of Food Safety:
    affiliation: Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Erik Garrison University of Tennesse Health Science Center:
    affiliation: - Erik Garrison - University of Tennesse Health Science Center
Prof. Luana Licata University of Rome “Tor Vergata”:
    affiliation: ELIXIR-IT, Italy
**Victoria Nugnes** University of Padova:
    affiliation: ELIXIR-IT, Italy
Marcella Bonanomi:
    affiliation: National Research Council – IBSBC Milan
Andrea Guarracino University of Tennesse Health Science Center:
    affiliation: - Andrea Guarracino - University of Tennesse Health Science Center
