Luca Alessandrì:
    affiliation: University of Turin, Italy
Marcella Bonanomi:
    affiliation: National Research Council – IBSBC Milan
Pierluigi Caboni:
    affiliation: University of Cagliari, Cagliari
Raffaele Calogero:
    affiliation: University of Turin, Italy
Anna Calì:
    affiliation: Agilent Technologies
Flavio A. Franchina:
    affiliation: University of Ferrara, Ferrara
Daniela Gaglio:
    affiliation: National Research Council – IBSBC Milan
Luigi Lucini:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Clara Musicco:
    affiliation: National Research Council – IBIOM, Bari
Roberto M. Pellegrino:
    affiliation: University of Perugia, Perugia
Leilei Zhang:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
