Adriano Fonzino:
    affiliation: University of Bari, Italy
Alessandro Silvestris:
    affiliation: University of Bari, Italy
Allegra Via:
    affiliation: Sapienza University of Rome, Italy
Andrea Guarracino:
    affiliation: University of Tennesse Health Science Center
Anna Calì:
    affiliation: Agilent Technologies
Arnold Knijn:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Camilla Ugolini:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Clara Musicco:
    affiliation: National Research Council – IBIOM, Bari
Daniela Gaglio:
    affiliation: National Research Council – IBSBC Milan
Erik Garrison:
    affiliation: University of Tennesse Health Science Center
Ernesto Picardi:
    affiliation: University of Bari, Italy
Fabiola De Marco:
    affiliation: Università di Salerno, Italy
Federica Quaglia:
    affiliation: University of Padova, ELIXIR-IT, Italy
Flavia Villani University of Tennesse Health Science Center:
    affiliation: - Flavia Villani - University of Tennesse Health Science Center
Flavio A. Franchina:
    affiliation: University of Ferrara, Ferrara
Francesco Nicassio:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Leilei Zhang:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Logan Mulroney:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Loredana Le Pera:
    affiliation: Core Facilities Technical-Scientific Service, National Institute of Health (FAST - ISS), Italy
Luca Alessandrì:
    affiliation: University of Turin, Italy
Luca De Sabato:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Luigi Lucini:
    affiliation: Università Cattolica del Sacro Cuore, Piacenza
Marcella Bonanomi:
    affiliation: National Research Council – IBSBC Milan
Maria Cristina Aspromonte:
    affiliation: University of Padova, ELIXIR-IT, Italy
Nancy D’Arminio:
    affiliation: Università di Salerno, Italy
Pierluigi Caboni:
    affiliation: University of Cagliari, Cagliari
Raffaele Calogero:
    affiliation: University of Turin, Italy
Roberto M. Pellegrino:
    affiliation: University of Perugia, Perugia
Teresa Colombo:
    affiliation: Istituto di Biologia e Patologia Molecolari (IBPM - CNR), ELIXIR-IT, Italy
Tommaso Leonardi:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Valeria Michelacci:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Victoria Nugnes:
    affiliation: University of Padova, ELIXIR-IT, Italy
