 Alessandrì Luca Alessandrì:
    affiliation: 
 Bonanomi Marcella Bonanomi:
    affiliation: 
 Caboni Pierluigi Caboni:
    affiliation: 
 Calogero Raffaele Calogero:
    affiliation: 
 Calì Anna Calì:
    affiliation: 
 Colombo Teresa Colombo:
    affiliation: 
 Cristina Aspromonte Maria Cristina Aspromonte:
    affiliation: 
 De Marco Fabiola De Marco:
    affiliation: 
 De Sabato Luca De Sabato:
    affiliation: 
 D’Arminio Nancy D’Arminio:
    affiliation: 
 Fonzino Adriano Fonzino:
    affiliation: 
 Franchina Flavio A. Franchina:
    affiliation: 
 Gaglio Daniela Gaglio:
    affiliation: 
 Garrison Erik Garrison:
    affiliation: 
 Guarracino Andrea Guarracino:
    affiliation: 
 Knijn Arnold Knijn:
    affiliation: 
 Le Pera Loredana Le Pera:
    affiliation: 
 Leonardi Tommaso Leonardi:
    affiliation: 
 Lucini Luigi Lucini:
    affiliation: 
 Michelacci Valeria Michelacci:
    affiliation: 
 Mulroney Logan Mulroney:
    affiliation: 
 Musicco Clara Musicco:
    affiliation: 
 Nicassio Francesco Nicassio:
    affiliation: 
 Nugnes Victoria Nugnes:
    affiliation: 
 Pellegrino Roberto M. Pellegrino:
    affiliation: 
 Picardi Ernesto Picardi:
    affiliation: 
 Quaglia Federica Quaglia:
    affiliation: 
 Silvestris Alessandro Silvestris:
    affiliation: 
 Ugolini Camilla Ugolini:
    affiliation: 
 Via Allegra Via:
    affiliation: 
 Villani University of Tennesse Health Science Center Flavia Villani University of Tennesse Health Science Center:
    affiliation: 
 Zhang Leilei Zhang:
    affiliation: 
