Victoria Nugnes:
    affiliation: University of Padova, ELIXIR-IT, Italy
Logan Mulroney:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Fabiola De Marco:
    affiliation: Università di Salerno, Italy
Raoul Bonnal:
    affiliation: IFOM - Research Computing & Data Science Manager
Tommaso Leonardi:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Maria Cristina Aspromonte:
    affiliation: University of Padova, ELIXIR-IT, Italy
Arnold Knijn:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Ernesto Picardi:
    affiliation: University of Bari, Italy
Francesco Nicassio:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Valeria Michelacci:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Erik Garrison:
    affiliation: University of Tennesse Health Science Center
Luana Licata:
    affiliation: University of Rome “Tor Vergata”, ELIXIR-IT, Italy
Allegra Via:
    affiliation: Sapienza University of Rome, Italy
Andrea Guarracino:
    affiliation: University of Tennesse Health Science Center
Adriano Fonzino:
    affiliation: University of Bari, Italy
Teresa Colombo:
    affiliation: Istituto di Biologia e Patologia Molecolari (IBPM - CNR), ELIXIR-IT, Italy
Camilla Ugolini:
    affiliation: Istituto Italiano di Tecnologia (IIT), Milano - Italy
Loredana Le Pera:
    affiliation: Core Facilities Technical-Scientific Service, National Institute of Health (FAST - ISS), Italy
Alessandro Silvestris:
    affiliation: University of Bari, Italy
Luca De Sabato:
    affiliation: Dep. of Food Safety, Nutrition and Veterinary Public Health, National Institute of Health (SANV - ISS), Italy
Federica Quaglia:
    affiliation: University of Padova, ELIXIR-IT, Italy
