Daniela Gaglio:
  affiliation: National Research Council – IBSBC Milan
Marcella Bonanomi:
  affiliation: National Research Council – IBSBC Milan
Flavio A. Franchina:
  affiliation: University of Ferrara, Ferrara
Luigi Lucini:
  affiliation: Università Cattolica del Sacro Cuore, Piacenza
Anna Calì:
  affiliation: Agilent Technologies
Leilei Zhang:
  affiliation: Università Cattolica del Sacro Cuore, Piacenza
Clara Musicco:
  affiliation: National Research Council – IBIOM, Bari
Pierluigi Caboni:
  affiliation: University of Cagliari, Cagliari
Roberto M. Pellegrino:
  affiliation: University of Perugia, Perugia
Raffaele Calogero:
  affiliation: University of Turin, Italy
Luca Alessandrì:
  affiliation: University of Turin, Italy
Ernesto Picardi:
  affiliation: University of Bari, Italy
Adriano Fonzino:
  affiliation: University of Bari, Italy
