name: Update TRAINERS.yaml
on:
  push:
    branches:
      - main # Trigger workflow on commits to main branch
jobs:
  update-trainers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install tools
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Extract trainers from Markdown
        run: |
          echo "Extracting trainers data..."
          > _data/TRAINERS.yaml # Clear existing TRAINERS.yaml
          # Iterate over .md files in the repository
          for file in $(find . -name '*.md'); do
            echo "Processing $file..."
            # Extract the 'Instructors' section
            trainers=$(grep -A10 -E "### Instructors {#instructors-section}" "$file" | grep -v "###")
            echo "$trainers" >> _data/TRAINERS.yaml
          done

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add _data/TRAINERS.yaml
          git commit -m "Update TRAINERS.yaml"
          git push

