name: Update TRAINERS.yaml
on:
  push:
    branches:
      - main # Trigger workflow on commits to main branch
jobs:
  update-trainers:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install tools
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Extract trainers from Markdown and sort by last name
        run: |
          echo "Extracting and sorting trainers data..."
          > _data/TRAINERS.yaml # Clear existing TRAINERS.yaml
          
          declare -A trainers_map # Create an associative array to store trainers

          # Process the most recent folder first
          for dir in pages/training_courses; do
            for file in $(find "$dir" -name '[0-9]*.md'); do
              if grep -q "### Instructor*" "$file"; then
                echo "Processing $file..."
                # Extract the 'Instructors' section
                trainers=$(grep -A10 -E "### Instructor*" "$file" | grep -v "###")
                
                # Populate trainers_map
                while IFS= read -r line; do
                  if [[ "$line" =~ ^- ]]; then
                    name=$(echo "$line" | cut -d',' -f1 | sed 's/- //g' | xargs)
                    affiliation=$(echo "$line" | cut -d',' -f2- | xargs)

                    # Add to trainers_map only if the name is not already present
                    if [[ -z "${trainers_map[$name]}" ]]; then
                      trainers_map["$name"]="$affiliation"
                    fi
                  fi
                done <<< "$trainers"
              fi
            done
          done

          # Sort trainers by last name and write to TRAINERS.yaml
          for name in "${!trainers_map[@]}" | awk '{print $2,$0}' | sort | awk '{$1=""; print $0}'; do
            echo "$name:" >> _data/TRAINERS.yaml
            echo "    affiliation: ${trainers_map[$name]}" >> _data/TRAINERS.yaml
          done




      - name: Commit changes
        run: |
          git config --global user.name 'elixir_training_bot'
          git config --global user.email 'elixir_training_bot@github.com'
          git add _data/TRAINERS.yaml
          git commit -m "Update TRAINERS.yaml"
          git push



